spring:
  profiles:
    active: local # Activate "local" profile by default
  jackson:
    default-property-inclusion: non_null
  messages:
    basename: i18n/messages
  mvc:
    # Throw NoHandlerFoundException
    # See https://stackoverflow.com/questions/36733254/spring-boot-rest-how-to-configure-404-resource-not-found#36734193
    throw-exception-if-no-handler-found: true
    problemdetails:
      enabled: true
  web:
    resources:
      # Throw NoHandlerFoundException
      # See https://stackoverflow.com/questions/36733254/spring-boot-rest-how-to-configure-404-resource-not-found#36734193
      add-mappings: false
  kafka:
    consumer:
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      # Determine which offset to start reading from if the offset doesn't exist on the server.
      # See https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html#auto-offset-reset
      auto-offset-reset: latest
    properties:
      # Deserialize to the generated Avro class rather than a GenericRecord type
      specific.avro.reader: true
server:
  tomcat:
    # Allow pipe character in URL to support passing commas such as "userId,asc"
    relaxed-query-chars: "|"
application:
  kafka:
    topic: products
    partitions: 2
    replicationFactor: 1
    groupId: consumer
