spring:
  # Only "spring.kafka.bootstrap-servers" works.
  # If "spring.kafka.producer.bootstrap-servers" was used, there would be an error "Connection to node -1 (localhost/127.0.0.1:9092) could not be established"
  # It's worth to look into Kafka's autoconfiguration to see why.
  kafka:
    bootstrap-servers: "kafka1:9092"
    properties:
      schema.registry.url: http://schema-registry:8081
logging:
  level:
    # Log Kafka
    org.springframework.kafka.listener: DEBUG
    org.springframework.kafka.listener.adapter: INFO
